---
title: "Current Conditions"
author: "Brian Froeb"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(sf)
library(tidyverse)
library(tmap)
library(rpgcolorsr)
library(rmapshaper)
library(scales)
library(mapdeck)

tmap_mode("view")
far_pal <- rpg_color_pal("rpg_orange_ramp")(10)
key <- paste0("pk.eyJ1IjoiYmZyb2ViLXJwZ3JvdXAiLCJhIjoiY2toY",
              "jM2ODUwMDN2bDJ5cGVpZjU4eWYzbSJ9.",
              "-Fm5keiE7dSTQXK45mI67A")
```

```{r data imports}
parcels  <- read_sf("./data/parcels.shp")
stations <- read_sf("./data/Stations.shp") 
stn_area <- read_sf("./data/StationAreas.shp") 
```

## Square Footage by Landuse 

## {.tabset}

### Exisiting
```{r Existing Sq Ft by LU}
#melt _Ex columns into long form then bar chart, include corridor and segment charts

parcels %>%
  select(seg_nam, ends_with("SF_Ex")) %>%
  st_drop_geometry() %>%
  pivot_longer(names_to = "land_use",
               cols = ends_with("Ex"),
               values_to = "square_ft") %>%
  mutate(land_use = str_sub(land_use, 1, -4)) %>%
  ggplot() +
  geom_col(aes(x = seg_nam, y = square_ft, fill = land_use)) +
  scale_fill_rpg(palette = "main and additional",
                 name    = "Land Use",
                 labels  = c("Hotel", "Industrial",
                             "Multi Family", "Office",
                             "Other", "Retail", "Single Family")) +
  scale_y_continuous(labels = comma) +
  ylab("Square Feet") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1),
        axis.title.x = element_blank())
```

```{r Exisiting FAR Map}
# attempting mapdeck
# parcels %>%
#   mutate(bld_area = SF_SF_Ex + MF_SF_Ex + Ret_SF_Ex + Ind_SF_Ex +
#                     Off_SF_Ex + Hot_SF_Ex + Oth_SF_Ex,
#          FAR      = bld_area / Sq_Feet)  %>%
#   fasterize(raster = raster, field = "FAR") %>%
#     tm_shape() + tm_polygon(col = "FAR",
#                              breaks = c(0, 0.25, 0.5, 1, 2, 900),
#                              labels = c("0 to 0.25", "0.25 to 0.50",
#                                         "0.50 to 1.00", "1.00 to 2.00",
#                                         "2.01 or more"),
#                              palette = far_pal,
#                            title = "Floor Area Ratio") +
#   tm_shape(stn_area) + tm_polygons(col = "#D3D3D3", alpha = 0.1) +
#   tm_shape(stations) + tm_dots()
mapdeck(token = key, 
        style = mapdeck_style("dark"),
        location = c(32.8, -79.9)) %>%
  add_sf(
    data = parcels %>%
      mutate(bld_area = SF_SF_Ex + MF_SF_Ex + Ret_SF_Ex + Ind_SF_Ex +
               Off_SF_Ex + Hot_SF_Ex + Oth_SF_Ex,
             FAR      = bld_area / Sq_Feet,
             FAR_Lab  = cut(FAR,
                            breaks = c(0, 0.25, 0.5, 1, 2, 900),
                            labels = c("[0-0.25)", "[0.25-0.5)",
                                       "[0.5-1", "[1-2)", "[2-900)"),
                            include.lowest = TRUE)) %>%
      st_transform(crs = 4326)
    , layer = "polygon_layer"
    , fill_colour = "FAR_Lab"
    , palette = "orrd"
    , legend = TRUE
    , legend_options = list(title = "Floor Area Ratio")
  ) %>%
  add_sf(
    data = stn_area %>% st_transform(crs = 4326)
    , layer = "station_areas"
    #, fill_colour ="#FFFFFF"
    , fill_opacity  = 0
    , stroke_colour = "#FFFFFF"
    , stroke_width  = 15
  ) %>%
  add_sf(
    data = stations %>% st_transform(crs = 4326)
    , layer = "stations"
    , fill_colour = "#D3D3D3"
    , fill_opacity = 255
    , radius_min_pixels = 8
    , radius_max_pixels = 12
  ) 
```

### Pipeline
```{r Pipeline Plot}
#summarize the pipe fields in the same way as the _EX columns
parcels %>% 
  select(seg_nam, contains("Pip", ignore.case = FALSE)) %>%
  st_drop_geometry() %>%
  pivot_longer(names_to = "land_use",
               cols = contains("Pip"),
               values_to = "square_ft") %>%
  mutate(land_use = str_replace(land_use, "_Pip.?", "")) %>%
  ggplot() +
  geom_col(aes(x = seg_nam, y = square_ft, fill = land_use)) +
  scale_fill_rpg(palette = "main and additional",
                 name    = "Land Use",
                 labels  = c("Hotel", "Industrial",
                             "Multi Family", "Office", 
                             "Other", "Retail", "Single Family")) +
  scale_y_continuous(labels = comma) +
  ylab("Square Feet") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1),
        axis.title.x = element_blank())
```

```{r Pipe FAR Map}
# parcels %>%
#   mutate(bld_area = SF_SF_Pipe + MF_SF_Pipe + Ret_SF_Pip + Ind_SF_Pip +
#                     Off_SF_Pip + Hot_SF_Pip + Oth_SF_Pip,
#          FAR      = bld_area / Sq_Feet) %>%
#   tm_shape() + tm_polygons(col = "FAR",
#                              lwd = 0.1,
#                              breaks = c(0, 0.25, 0.5, 1, 2, 900),
#                              labels = c("0 to 0.25", "0.25 to 0.50", 
#                                         "0.50 to 1.00", "1.00 to 2.00", 
#                                         "2.01 or more"),
#                              palette = far_pal,
#                            title = "Floor Area Ratio") +
#   tm_shape(stn_area) + tm_polygons(col = "#D3D3D3", alpha = 0.1) + 
#   tm_shape(stations) + tm_dots()

mapdeck(token = key, 
        style = mapdeck_style("dark"),
        location = c(32.8, -79.9)) %>%
  add_sf(
    data = parcels %>%
      mutate(bld_area = SF_SF_Pipe + MF_SF_Pipe + Ret_SF_Pip + Ind_SF_Pip +
                        Off_SF_Pip + Hot_SF_Pip + Oth_SF_Pip,
             FAR      = bld_area / Sq_Feet,
             FAR_Lab  = cut(FAR,
                            breaks = c(0, 0.25, 0.5, 1, 2, 900),
                            labels = c("[0-0.25)", "[0.25-0.5)",
                                       "[0.5-1", "[1-2)", "[2-900)"),
                            include.lowest = TRUE)) %>%
      st_transform(crs = 4326)
    , layer = "polygon_layer"
    , fill_colour = "FAR_Lab"
    , palette = "orrd"
    , legend = TRUE
    , legend_options = list(title = "Floor Area Ratio")
  ) %>%
  add_sf(
    data = stn_area %>% st_transform(crs = 4326)
    , layer = "station_areas"
    #, fill_colour ="#FFFFFF"
    , fill_opacity  = 0
    , stroke_colour = "#FFFFFF"
    , stroke_width  = 15
  ) %>%
  add_sf(
    data = stations %>% st_transform(crs = 4326)
    , layer = "stations"
    , fill_colour = "#D3D3D3"
    , fill_opacity = 255
    , radius_min_pixels = 8
    , radius_max_pixels = 12
  ) 
```

### Pipe and Exisiting
```{r Pipe EX Plot}
#summarize the EX Pipe fields in the same way as the _EX columns
parcels %>% 
  select(seg_nam, contains("SF_ExP")) %>%
  st_drop_geometry() %>%
  pivot_longer(names_to = "land_use",
               cols = contains("ExP"),
               values_to = "square_ft") %>%
  mutate(land_use = str_replace(land_use, "_ExP.?", "")) %>%
  
  ggplot() +
  geom_col(aes(x = seg_nam, y = square_ft, fill = land_use)) +
  scale_fill_rpg(palette = "main and additional",
                 name    = "Land Use",
                 labels  = c("Hotel", "Industrial",
                             "Multi Family", "Office", 
                             "Other", "Retail", "Single Family")) +
  scale_y_continuous(labels = comma) +
  ylab("Square Feet") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1),
        axis.title.x = element_blank())
```

```{r Pipe EX FAR Map}
# parcels %>%
#   mutate(bld_area = SF_SF_ExPi + MF_SF_ExPi + Ret_SF_ExP + Ind_SF_ExP +
#                     Off_SF_ExP + Hot_SF_ExP + Oth_SF_ExP,
#          FAR      = bld_area / Sq_Feet) %>%
#   tm_shape() + tm_polygons(col = "FAR",
#                              lwd = 0.1,
#                              breaks = c(0, 0.25, 0.5, 1, 2, 900),
#                              labels = c("0 to 0.25", "0.25 to 0.50", 
#                                         "0.50 to 1.00", "1.00 to 2.00", 
#                                         "2.01 or more"),
#                              palette = far_pal,
#                            title = "Floor Area Ratio") +
#   tm_shape(stn_area) + tm_polygons(col = "#D3D3D3", alpha = 0.1) + 
#   tm_shape(stations) + tm_dots()

mapdeck(token = key, 
        style = mapdeck_style("dark"),
        location = c(32.8, -79.9)) %>%
  add_sf(
    data = parcels %>%
      mutate(bld_area = SF_SF_ExPi + MF_SF_ExPi + Ret_SF_ExP + Ind_SF_ExP +
                        Off_SF_ExP + Hot_SF_ExP + Oth_SF_ExP,
             FAR      = bld_area / Sq_Feet,
             FAR_Lab  = cut(FAR,
                            breaks = c(0, 0.25, 0.5, 1, 2, 900),
                            labels = c("[0-0.25)", "[0.25-0.5)",
                                       "[0.5-1", "[1-2)", "[2-900)"),
                            include.lowest = TRUE)) %>%
      st_transform(crs = 4326)
    , layer = "polygon_layer"
    , fill_colour = "FAR_Lab"
    , palette = "orrd"
    , legend = TRUE
    , legend_options = list(title = "Floor Area Ratio")
  ) %>%
  add_sf(
    data = stn_area %>% st_transform(crs = 4326)
    , layer = "station_areas"
    #, fill_colour ="#FFFFFF"
    , fill_opacity  = 0
    , stroke_colour = "#FFFFFF"
    , stroke_width  = 15
  ) %>%
  add_sf(
    data = stations %>% st_transform(crs = 4326)
    , layer = "stations"
    , fill_colour = "#D3D3D3"
    , fill_opacity = 255
    , radius_min_pixels = 8
    , radius_max_pixels = 12
  ) 
```
